In [1]:
import pandas as pd
import numpy as np

# Question 1

In [2]:
def range_series(*args):
    
    if args[0] == 'None':
        null = pd.Series(range(1,11))
        return null
    elif len(args) == 1:
        single = pd.Series(range(args[0],11))
        return single
    elif len(args) == 2:
        add = 0
        for a in args:
            add = add + a
        both = pd.Series(range(args[0],add+1))
        return both
  
  
start = []
start = input("enter range: ")
start = start.split()
start = np.asarray(start, dtype=int)
if len(start) == 0:
    print(range_series('None'))   
elif len(start) > 2:
    print("enter only start and end.")
    print(range_series('None'))   
elif len(start) == 1:
    print(range_series(start[0]))
else:
    first = start[0]
    last = start[1]
    print(range_series(first, last))


enter range: 
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64


In [3]:
def addition(*args):
    result = 0
    for num in args:
        result += num
    print(result)


a = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
addition(a,b)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


# Question 2

In [4]:
keys = ['first','second','third']
values = ['apple','banana','mango']
df = pd.DataFrame([values],columns = [keys])
df

first  second  third
0  apple  banana  mango

In [5]:
data = pd.DataFrame(['One','Two'],[["X","Y"],["A","B"]])
# data1 = pd.DataFrame([data[1]],columns = [data[0]])
data.values

array([['One'],
       ['Two']], dtype=object)

In [6]:
data1 = data.T
dfc= data1.columns
dfc

MultiIndex([('X', 'A'),
            ('Y', 'B')],
           )

In [7]:
dfv = data1.values
dfv

array([['One', 'Two']], dtype=object)

In [8]:
df = pd.DataFrame(dfc,columns = dfv)
df

(One, Two)
0     (X, A)
1     (Y, B)

# Question 3


In [9]:
a = np.arange(1,10).reshape(3,3)
df1 = pd.DataFrame(a,columns = ['set1','set2','set3'],index=[1,2,3])
df1
b = np.arange(11,20).reshape(3,3)
df2 = pd.DataFrame(b,columns = ['set4','set5','set6'],index = [4,5,6])
df2

set4  set5  set6
4    11    12    13
5    14    15    16
6    17    18    19

In [10]:
c = pd.concat([df1,df2],axis = 0)
c

set1  set2  set3  set4  set5  set6
1   1.0   2.0   3.0   NaN   NaN   NaN
2   4.0   5.0   6.0   NaN   NaN   NaN
3   7.0   8.0   9.0   NaN   NaN   NaN
4   NaN   NaN   NaN  11.0  12.0  13.0
5   NaN   NaN   NaN  14.0  15.0  16.0
6   NaN   NaN   NaN  17.0  18.0  19.0

# Question 4

In [11]:
data = pd.read_csv("../datasets/cars.csv")
data.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [12]:
data1 = pd.DataFrame(data.describe())
data1

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

# Question 5

In [17]:
correlation = data.corr()
correlation

/tmp/ipykernel_10366/3106392754.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation = data.corr()


mpg       cyl      disp        hp      drat        wt      qsec  \
mpg   1.000000 -0.852162 -0.847551 -0.776168  0.681172 -0.867659  0.418684   
cyl  -0.852162  1.000000  0.902033  0.832447 -0.699938  0.782496 -0.591242   
disp -0.847551  0.902033  1.000000  0.790949 -0.710214  0.887980 -0.433698   
hp   -0.776168  0.832447  0.790949  1.000000 -0.448759  0.658748 -0.708223   
drat  0.681172 -0.699938 -0.710214 -0.448759  1.000000 -0.712441  0.091205   
wt   -0.867659  0.782496  0.887980  0.658748 -0.712441  1.000000 -0.174716   
qsec  0.418684 -0.591242 -0.433698 -0.708223  0.091205 -0.174716  1.000000   
vs    0.664039 -0.810812 -0.710416 -0.723097  0.440278 -0.554916  0.744535   
am    0.599832 -0.522607 -0.591227 -0.243204  0.712711 -0.692495 -0.229861   
gear  0.480285 -0.492687 -0.555569 -0.125704  0.699610 -0.583287 -0.212682   
carb -0.550925  0.526988  0.394977  0.749812 -0.090790  0.427606 -0.656249   

            vs        am      gear      carb  
mpg   0.664039  0.599832  0.480285 -0.550925  
cyl  -0.810812 -0.522607 -0.492687  0.526988  
disp -0.710416 -0.591227 -0.555569  0.394977  
hp   -0.723097 -0.243204 -0.125704  0.749812  
drat  0.440278  0.712711  0.699610 -0.090790  
wt   -0.554916 -0.692495 -0.583287  0.427606  
qsec  0.744535 -0.229861 -0.212682 -0.656249  
vs    1.000000  0.168345  0.206023 -0.569607  
am    0.168345  1.000000  0.794059  0.057534  
gear  0.206023  0.794059  1.000000  0.274073  
carb -0.569607  0.057534  0.274073  1.000000

In [48]:
def func(column):
    unstacked = correlation.unstack().sort_values(ascending = False) 
    return unstacked[column].index[1]
func('mpg')

'drat'

In [49]:
# def corrr(columns):
#     unstacked = correlation.unstack().sort_values(ascending = False) 
#     names = []
#     for i in columns:
#         got = unstacked[i].index[1]
#         names.append(got)
#     return names
    
    
# corrr(correlation.columns)