In [2]:
import numpy as np

# Question 1

In [3]:
a = np.arange(2,11).reshape(3,3)
a

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

# Question 2

In [4]:
a = input("enter num: ")
type(a)
arr1 = a.split()
f = np.asarray(arr1, dtype=float)
f


enter num: 1 2 3 4


array([1., 2., 3., 4.])

# Question 3

In [6]:
a = np.array([10,20,30])
b = np.array([40,50,60,70])
c = np.append(a,b)
c

array([10, 20, 30, 40, 50, 60, 70])

# Question 4

In [13]:
a = np.array([10,20,30])
b = np.array([40,50,60])
sum_array1 = np.sum([a,b],axis = 0)
sum_array2 = np.sum([a,b],axis = 1)

In [14]:
arr = np.arange(10,100,10).reshape(3,3)
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
arr[0]

array([10, 20, 30])

In [16]:
arr[-1,-1]

90